opencti:
  url: #ChangeMe
  token: #ChangeMe
  ssl_verify: true

connector:
  queue_protocol: api
  type: 'EXTERNAL_IMPORT'
  id: #ChangeMe
  name: 'LOPM Connector'
  scope: 'domain-name'
  log_level: 'debug' # optional (default: 'error')
  duration_period: 'PT24H' #  # optional, interval in ISO-8601 format between two runs of the connector (default: 'PT1H')

lopmconnector:
  #api_base_url: 'https://example.com'
  #api_key: #ChangeMe
  tlp_level: 'clear' # optional, available values: 'clear', 'white', 'green', 'amber', 'amber+strict', 'red' (default: 'clear')
